<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Helper\Helper.csproj" />
    <ProjectReference Include="..\TrustQuarantine\TrustQuarantine.csproj" />
    <ProjectReference Include="..\..\Xdows-Model\Xdows-Model-Invoker\Xdows-Model-Invoker.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="System.Management" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\Xdows-Model\Xdows-Model-Invoker\Xdows-Model.onnx" Condition="Exists('..\..\Xdows-Model\Xdows-Model-Invoker\Xdows-Model.onnx')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <Link>Xdows-Model.onnx</Link>
    </Content>
    <Content Include="..\..\Xdows-Model\Xdows-Model-Invoker\Xdows-Model-Flash.onnx" Condition="Exists('..\..\Xdows-Model\Xdows-Model-Invoker\Xdows-Model-Flash.onnx')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <Link>Xdows-Model-Flash.onnx</Link>
    </Content>
    <Content Include="..\..\Xdows-Model\Xdows-Model-Invoker\Xdows-Model-Pro.onnx" Condition="Exists('..\..\Xdows-Model\Xdows-Model-Invoker\Xdows-Model-Pro.onnx')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <Link>Xdows-Model-Pro.onnx</Link>
    </Content>
    <Content Include="..\..\Xdows-Model\Xdows-Model-Invoker\Xdows-Model-Pro-*.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <Link>%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>

  <Target Name="RemoveDia2LibFromPublish" AfterTargets="ResolveReferences">
    <ItemGroup>
      <ReferenceCopyLocalPaths Remove="@(ReferenceCopyLocalPaths)" Condition="$([System.String]::new('%(Filename)').StartsWith('Dia2Lib'))" />
    </ItemGroup>
  </Target>

</Project>
